-- Mountain Weather Decision V5.1 anonymous usage analytics
-- Run this once in Supabase: SQL Editor > New query > Run.

create table if not exists public.usage_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  session_id text not null,
  app_version text,
  event_name text not null,
  success boolean,
  duration_ms integer,
  mountain text,
  route_points integer,
  stay_count integer,
  error_message text,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists usage_events_created_at_idx
  on public.usage_events (created_at desc);
create index if not exists usage_events_event_name_idx
  on public.usage_events (event_name);
create index if not exists usage_events_mountain_idx
  on public.usage_events (mountain);

alter table public.usage_events enable row level security;
-- No public INSERT/SELECT policy is created.
-- The app writes only from server.py with the Supabase service-role key.

create or replace view public.usage_daily_summary as
select
  date_trunc('day', created_at) as day,
  count(*) filter (where event_name = 'page_view') as page_views,
  count(*) filter (where event_name = 'route_created' and success is true) as routes_created,
  count(*) filter (where event_name = 'trail_route_calculated' and success is true) as trail_routes_ok,
  count(*) filter (where event_name = 'weather_analysis' and success is true) as analyses_ok,
  count(*) filter (where success is false) as failures,
  round(avg(duration_ms) filter (where duration_ms is not null)) as avg_duration_ms
from public.usage_events
group by 1
order by 1 desc;
